# Generated by Django 6.0.7 on 2026-07-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
