# Generated by Django 6.0.7 on 2026-07-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='confirmpassword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
