# Generated by Django 6.0.7 on 2026-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registermodel_otp_created_at_registermodel_reset_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='confirmpassword',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
