# Generated by Django 6.0.7 on 2026-08-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_registermodel_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='confirmpassword',
        ),
    ]
