# Generated by Django 6.0.7 on 2026-08-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_registermodel_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRoomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='ai_rooms/original/')),
                ('room_type', models.CharField(choices=[('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Study Room', 'Study Room'), ('Bathroom', 'Bathroom'), ('Office', 'Office')], max_length=30)),
                ('design_style', models.CharField(choices=[('Modern', 'Modern'), ('Minimalist', 'Minimalist'), ('Luxury', 'Luxury'), ('Scandinavian', 'Scandinavian'), ('Industrial', 'Industrial'), ('Traditional', 'Traditional')], max_length=30)),
                ('prompt', models.TextField()),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='ai_rooms/generated/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_room_designs', to='myapp.registermodel')),
            ],
        ),
    ]
