# Generated by Django 6.0.7 on 2026-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_airoomdesign_generated_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airoomdesign',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_rooms/generated/'),
        ),
        migrations.AlterField(
            model_name='airoomdesign',
            name='original_image',
            field=models.ImageField(upload_to='ai_rooms/original/'),
        ),
    ]
