# Generated by Django 6.0.7 on 2026-08-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_airoomdesign_generated_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airoomdesign',
            name='generated_image',
        ),
        migrations.AlterField(
            model_name='airoomdesign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
