# Generated by Django 6.0.7 on 2026-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_airoomdesign_generated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airoomdesign',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_rooms/generated/'),
        ),
    ]
