# Generated by Django 6.0.7 on 2026-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_airoomdesign_generated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='airoomdesign',
            name='budget',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Medium', 'Medium'), ('Premium', 'Premium')], default='Medium', max_length=30),
        ),
        migrations.AddField(
            model_name='airoomdesign',
            name='color_theme',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('Warm', 'Warm'), ('Cool', 'Cool'), ('White', 'White'), ('Earthy', 'Earthy'), ('Dark', 'Dark')], default='Neutral', max_length=30),
        ),
        migrations.AddField(
            model_name='airoomdesign',
            name='lighting',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Warm', 'Warm'), ('Bright', 'Bright'), ('Ambient', 'Ambient')], default='Natural', max_length=30),
        ),
    ]
