# Generated by Django 6.0.7 on 2026-08-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_airoomdesign_budget_airoomdesign_color_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airoomdesign',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
