# Generated by Django 6.0.7 on 2026-08-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_airoomdesign_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='airoomdesign',
            name='parent_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='myapp.airoomdesign'),
        ),
        migrations.AddField(
            model_name='airoomdesign',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
