from django.urls import path
from . import views
urlpatterns = [
    path("login", views.loginpage,name='login'),
    # path("forgotpwd", views.forgotpwd),
    # path("forgotpassword", views.forgotpassword),

    path("Register", views.registerpage, name="registerpage"),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("verify-otp/", views.verify_otp, name="verify_otp"),
    path("new-password/", views.new_password, name="new_password"),
    path("logout",views.logout),
    path("fetchregisterdata", views.fetchregisterdata),
    path("checklogindata", views.checklogindata),
    path("",views.indexpage),
    path("about/",views.aboutpage),
    path("Residential",views.Residentialpage),
    path("Commercial",views.Commercialpage),
    path("addpackage",views.addpackagepage),
    path("fetchpackagedata",views.fetchpackagedata),
    path("showpackage",views.showpackage),
    path("mypackages",views.mypackages),
    path("singlepackage/<int:id>",views.singlepackagepage),
    path("categorywisepackage/<int:id>",views.categorywisepackagepage),
    path("managepackage",views.managepackagepage),
    path("deletepackage/<int:id>",views.deletepackage),
    path("addportfolio", views.addportfoliopage),
    path("fetchportfoliodata", views.fetchportfoliodata),
    path("showportfolio/", views.showportfoliopage,name='showportfolio'),
    path("singleportfolio/<int:id>", views.singleportfoliopage),
    path("categorywiseportfolio/<int:id>",views.categorywiseportfolio),
    path("myportfolios",views.myportfolios),
    path("manageportfolio",views.manageportfoliopage),
    path("deleteportfolio/<int:id>",views.deleteportfolio),
    path("contact",views.contactpage),
    path("fetchcontactdata",views.fetchcontactdata),
    path("booking/<int:pack_id>",views.bookingpage),
    path("featchbooking",views.featchbooking),
    path('payment-success/', views.payment_success, name='payment-success'),
    path('payment-page/<str:order_id>/', views.payment_page, name='payment_page'),
    path("managebooking",views.managebookingpage),
    path("managebookings",views.desmanagebookingpage),
    path("insertintobooking",views.insertintobooking),
    path('full_image/<int:package_id>/', views.full_image_view, name='full_image'),
    path("Review",views.reviewpage),
    path("fetchratingpagedata",views.fetchreviewdata),
    path("managereview",views.managereviewpage),
    path("thankyou",views.thankyoupage),
    path('payment-history', views.payment_history, name='payment_history'),
    path('edit-package/<int:package_id>/', views.edit_package, name='edit_package'),
    path('editportfolio/<int:portfolio_id>/', views.edit_portfolio, name='editportfolio'),
    path('updateportfolio/<int:portfolio_id>/', views.update_portfolio, name='updateportfolio'),
    path("cancelbooking/<int:id>", views.cancelbooking, name="cancelbooking"),
    path("ShowReview",views.showreview),
    path("ai-room-designer/",views.ai_room_designer, name="ai_room_designer"),
    path("ai-room-result/<int:design_id>/",views.ai_room_result,name="ai_room_result"),
    path("ai-room-history/",views.ai_room_history,name="ai_room_history"),
    path("ai-room-edit/<int:design_id>/",views.ai_room_edit,name="ai_room_edit"),
    path("ai-room-save/<int:design_id>/",views.save_ai_design,name="save_ai_design"),
    path("ai-saved-designs/",views.ai_saved_designs,name="ai_saved_designs"),
    path("ai-room-versions/<int:design_id>/",views.ai_room_versions,name="ai_room_versions"),
    path("ai-room-delete/<int:design_id>/", views.delete_ai_design, name="delete_ai_design"),
]